#encoding: utf-8

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Populate countries table

Country.find_or_create_by({ code: "af", name: "Afghanistan" })
Country.find_or_create_by({ code: "ax", name: "Åland Islands" })
Country.find_or_create_by({ code: "al", name: "Albania" })
Country.find_or_create_by({ code: "dz", name: "Algeria" })
Country.find_or_create_by({ code: "as", name: "American Samoa" })
Country.find_or_create_by({ code: "ad", name: "Andorra" })
Country.find_or_create_by({ code: "ao", name: "Angola" })
Country.find_or_create_by({ code: "ai", name: "Anguilla" })
Country.find_or_create_by({ code: "aq", name: "Antarctica" })
Country.find_or_create_by({ code: "ag", name: "Antigua and Barbuda" })
Country.find_or_create_by({ code: "ar", name: "Argentina" })
Country.find_or_create_by({ code: "am", name: "Armenia" })
Country.find_or_create_by({ code: "aw", name: "Aruba" })
Country.find_or_create_by({ code: "au", name: "Australia" })
Country.find_or_create_by({ code: "at", name: "Austria" })
Country.find_or_create_by({ code: "az", name: "Azerbaijan" })
Country.find_or_create_by({ code: "bs", name: "Bahamas" })
Country.find_or_create_by({ code: "bh", name: "Bahrain" })
Country.find_or_create_by({ code: "bd", name: "Bangladesh" })
Country.find_or_create_by({ code: "bb", name: "Barbados" })
Country.find_or_create_by({ code: "by", name: "Belarus" })
Country.find_or_create_by({ code: "be", name: "Belgium" })
Country.find_or_create_by({ code: "bz", name: "Belize" })
Country.find_or_create_by({ code: "bj", name: "Benin" })
Country.find_or_create_by({ code: "bm", name: "Bermuda" })
Country.find_or_create_by({ code: "bt", name: "Bhutan" })
Country.find_or_create_by({ code: "bo", name: "Bolivia, Plurinational State of" })
Country.find_or_create_by({ code: "bq", name: "Bonaire, Sint Eustatius and Saba" })
Country.find_or_create_by({ code: "ba", name: "Bosnia and Herzegovina" })
Country.find_or_create_by({ code: "bw", name: "Botswana" })
Country.find_or_create_by({ code: "bv", name: "Bouvet Island" })
Country.find_or_create_by({ code: "br", name: "Brazil" })
Country.find_or_create_by({ code: "io", name: "British Indian Ocean Territory" })
Country.find_or_create_by({ code: "bn", name: "Brunei Darussalam" })
Country.find_or_create_by({ code: "bg", name: "Bulgaria" })
Country.find_or_create_by({ code: "bf", name: "Burkina Faso" })
Country.find_or_create_by({ code: "bi", name: "Burundi" })
Country.find_or_create_by({ code: "kh", name: "Cambodia" })
Country.find_or_create_by({ code: "cm", name: "Cameroon" })
Country.find_or_create_by({ code: "ca", name: "Canada" })
Country.find_or_create_by({ code: "cv", name: "Cape Verde" })
Country.find_or_create_by({ code: "ky", name: "Cayman Islands" })
Country.find_or_create_by({ code: "cf", name: "Central African Republic" })
Country.find_or_create_by({ code: "td", name: "Chad" })
Country.find_or_create_by({ code: "cl", name: "Chile" })
Country.find_or_create_by({ code: "cn", name: "China" })
Country.find_or_create_by({ code: "cx", name: "Christmas Island" })
Country.find_or_create_by({ code: "cc", name: "Cocos (Keeling) Islands" })
Country.find_or_create_by({ code: "co", name: "Colombia" })
Country.find_or_create_by({ code: "km", name: "Comoros" })
Country.find_or_create_by({ code: "cg", name: "Congo" })
Country.find_or_create_by({ code: "cd", name: "Congo, the Democratic Republic of the" })
Country.find_or_create_by({ code: "ck", name: "Cook Islands" })
Country.find_or_create_by({ code: "cr", name: "Costa Rica" })
Country.find_or_create_by({ code: "ci", name: "Côte d'Ivoire" })
Country.find_or_create_by({ code: "hr", name: "Croatia" })
Country.find_or_create_by({ code: "cu", name: "Cuba" })
Country.find_or_create_by({ code: "cw", name: "Curaçao" })
Country.find_or_create_by({ code: "cy", name: "Cyprus" })
Country.find_or_create_by({ code: "cz", name: "Czech Republic" })
Country.find_or_create_by({ code: "dk", name: "Denmark" })
Country.find_or_create_by({ code: "dj", name: "Djibouti" })
Country.find_or_create_by({ code: "dm", name: "Dominica" })
Country.find_or_create_by({ code: "do", name: "Dominican Republic" })
Country.find_or_create_by({ code: "ec", name: "Ecuador" })
Country.find_or_create_by({ code: "eg", name: "Egypt" })
Country.find_or_create_by({ code: "sv", name: "El Salvador" })
Country.find_or_create_by({ code: "gq", name: "Equatorial Guinea" })
Country.find_or_create_by({ code: "er", name: "Eritrea" })
Country.find_or_create_by({ code: "ee", name: "Estonia" })
Country.find_or_create_by({ code: "et", name: "Ethiopia" })
Country.find_or_create_by({ code: "fk", name: "Falkland Islands (Malvinas)" })
Country.find_or_create_by({ code: "fo", name: "Faroe Islands" })
Country.find_or_create_by({ code: "fj", name: "Fiji" })
Country.find_or_create_by({ code: "fi", name: "Finland" })
Country.find_or_create_by({ code: "fr", name: "France" })
Country.find_or_create_by({ code: "gf", name: "French Guiana" })
Country.find_or_create_by({ code: "pf", name: "French Polynesia" })
Country.find_or_create_by({ code: "tf", name: "French Southern Territories" })
Country.find_or_create_by({ code: "ga", name: "Gabon" })
Country.find_or_create_by({ code: "gm", name: "Gambia" })
Country.find_or_create_by({ code: "ge", name: "Georgia" })
Country.find_or_create_by({ code: "de", name: "Germany" })
Country.find_or_create_by({ code: "gh", name: "Ghana" })
Country.find_or_create_by({ code: "gi", name: "Gibraltar" })
Country.find_or_create_by({ code: "gr", name: "Greece" })
Country.find_or_create_by({ code: "gl", name: "Greenland" })
Country.find_or_create_by({ code: "gd", name: "Grenada" })
Country.find_or_create_by({ code: "gp", name: "Guadeloupe" })
Country.find_or_create_by({ code: "gu", name: "Guam" })
Country.find_or_create_by({ code: "gt", name: "Guatemala" })
Country.find_or_create_by({ code: "gg", name: "Guernsey" })
Country.find_or_create_by({ code: "gn", name: "Guinea" })
Country.find_or_create_by({ code: "gw", name: "Guinea-Bissau" })
Country.find_or_create_by({ code: "gy", name: "Guyana" })
Country.find_or_create_by({ code: "ht", name: "Haiti" })
Country.find_or_create_by({ code: "hm", name: "Heard Island and McDonald Islands" })
Country.find_or_create_by({ code: "va", name: "Holy See (Vatican City State)" })
Country.find_or_create_by({ code: "hn", name: "Honduras" })
Country.find_or_create_by({ code: "hk", name: "Hong Kong" })
Country.find_or_create_by({ code: "hu", name: "Hungary" })
Country.find_or_create_by({ code: "is", name: "Iceland" })
Country.find_or_create_by({ code: "in", name: "India" })
Country.find_or_create_by({ code: "id", name: "Indonesia" })
Country.find_or_create_by({ code: "ir", name: "Iran, Islamic Republic of" })
Country.find_or_create_by({ code: "iq", name: "Iraq" })
Country.find_or_create_by({ code: "ie", name: "Ireland" })
Country.find_or_create_by({ code: "im", name: "Isle of Man" })
Country.find_or_create_by({ code: "il", name: "Israel" })
Country.find_or_create_by({ code: "it", name: "Italy" })
Country.find_or_create_by({ code: "jm", name: "Jamaica" })
Country.find_or_create_by({ code: "jp", name: "Japan" })
Country.find_or_create_by({ code: "je", name: "Jersey" })
Country.find_or_create_by({ code: "jo", name: "Jordan" })
Country.find_or_create_by({ code: "kz", name: "Kazakhstan" })
Country.find_or_create_by({ code: "ke", name: "Kenya" })
Country.find_or_create_by({ code: "ki", name: "Kiribati" })
Country.find_or_create_by({ code: "kp", name: "Korea, Democratic People's Republic of" })
Country.find_or_create_by({ code: "kr", name: "Korea, Republic of" })
Country.find_or_create_by({ code: "kw", name: "Kuwait" })
Country.find_or_create_by({ code: "kg", name: "Kyrgyzstan" })
Country.find_or_create_by({ code: "la", name: "Lao People's Democratic Republic" })
Country.find_or_create_by({ code: "lv", name: "Latvia" })
Country.find_or_create_by({ code: "lb", name: "Lebanon" })
Country.find_or_create_by({ code: "ls", name: "Lesotho" })
Country.find_or_create_by({ code: "lr", name: "Liberia" })
Country.find_or_create_by({ code: "ly", name: "Libya" })
Country.find_or_create_by({ code: "li", name: "Liechtenstein" })
Country.find_or_create_by({ code: "lt", name: "Lithuania" })
Country.find_or_create_by({ code: "lu", name: "Luxembourg" })
Country.find_or_create_by({ code: "mo", name: "Macao" })
Country.find_or_create_by({ code: "mk", name: "Macedonia, the former Yugoslav Republic of" })
Country.find_or_create_by({ code: "mg", name: "Madagascar" })
Country.find_or_create_by({ code: "mw", name: "Malawi" })
Country.find_or_create_by({ code: "my", name: "Malaysia" })
Country.find_or_create_by({ code: "mv", name: "Maldives" })
Country.find_or_create_by({ code: "ml", name: "Mali" })
Country.find_or_create_by({ code: "mt", name: "Malta" })
Country.find_or_create_by({ code: "mh", name: "Marshall Islands" })
Country.find_or_create_by({ code: "mq", name: "Martinique" })
Country.find_or_create_by({ code: "mr", name: "Mauritania" })
Country.find_or_create_by({ code: "mu", name: "Mauritius" })
Country.find_or_create_by({ code: "yt", name: "Mayotte" })
Country.find_or_create_by({ code: "mx", name: "Mexico" })
Country.find_or_create_by({ code: "fm", name: "Micronesia, Federated States of" })
Country.find_or_create_by({ code: "md", name: "Moldova, Republic of" })
Country.find_or_create_by({ code: "mc", name: "Monaco" })
Country.find_or_create_by({ code: "mn", name: "Mongolia" })
Country.find_or_create_by({ code: "me", name: "Montenegro" })
Country.find_or_create_by({ code: "ms", name: "Montserrat" })
Country.find_or_create_by({ code: "ma", name: "Morocco" })
Country.find_or_create_by({ code: "mz", name: "Mozambique" })
Country.find_or_create_by({ code: "mm", name: "Myanmar" })
Country.find_or_create_by({ code: "na", name: "Namibia" })
Country.find_or_create_by({ code: "nr", name: "Nauru" })
Country.find_or_create_by({ code: "np", name: "Nepal" })
Country.find_or_create_by({ code: "nl", name: "Netherlands" })
Country.find_or_create_by({ code: "nc", name: "New Caledonia" })
Country.find_or_create_by({ code: "nz", name: "New Zealand" })
Country.find_or_create_by({ code: "ni", name: "Nicaragua" })
Country.find_or_create_by({ code: "ne", name: "Niger" })
Country.find_or_create_by({ code: "ng", name: "Nigeria" })
Country.find_or_create_by({ code: "nu", name: "Niue" })
Country.find_or_create_by({ code: "nf", name: "Norfolk Island" })
Country.find_or_create_by({ code: "mp", name: "Northern Mariana Islands" })
Country.find_or_create_by({ code: "no", name: "Norway" })
Country.find_or_create_by({ code: "om", name: "Oman" })
Country.find_or_create_by({ code: "pk", name: "Pakistan" })
Country.find_or_create_by({ code: "pw", name: "Palau" })
Country.find_or_create_by({ code: "ps", name: "Palestine, State of" })
Country.find_or_create_by({ code: "pa", name: "Panama" })
Country.find_or_create_by({ code: "pg", name: "Papua New Guinea" })
Country.find_or_create_by({ code: "py", name: "Paraguay" })
Country.find_or_create_by({ code: "pe", name: "Peru" })
Country.find_or_create_by({ code: "ph", name: "Philippines" })
Country.find_or_create_by({ code: "pn", name: "Pitcairn" })
Country.find_or_create_by({ code: "pl", name: "Poland" })
Country.find_or_create_by({ code: "pt", name: "Portugal" })
Country.find_or_create_by({ code: "pr", name: "Puerto Rico" })
Country.find_or_create_by({ code: "qa", name: "Qatar" })
Country.find_or_create_by({ code: "re", name: "Réunion" })
Country.find_or_create_by({ code: "ro", name: "Romania" })
Country.find_or_create_by({ code: "ru", name: "Russian Federation" })
Country.find_or_create_by({ code: "rw", name: "Rwanda" })
Country.find_or_create_by({ code: "bl", name: "Saint Barthélemy" })
Country.find_or_create_by({ code: "sh", name: "Saint Helena, Ascension and Tristan da Cunha" })
Country.find_or_create_by({ code: "kn", name: "Saint Kitts and Nevis" })
Country.find_or_create_by({ code: "lc", name: "Saint Lucia" })
Country.find_or_create_by({ code: "mf", name: "Saint Martin (French part)" })
Country.find_or_create_by({ code: "pm", name: "Saint Pierre and Miquelon" })
Country.find_or_create_by({ code: "vc", name: "Saint Vincent and the Grenadines" })
Country.find_or_create_by({ code: "ws", name: "Samoa" })
Country.find_or_create_by({ code: "sm", name: "San Marino" })
Country.find_or_create_by({ code: "st", name: "Sao Tome and Principe" })
Country.find_or_create_by({ code: "sa", name: "Saudi Arabia" })
Country.find_or_create_by({ code: "sn", name: "Senegal" })
Country.find_or_create_by({ code: "rs", name: "Serbia" })
Country.find_or_create_by({ code: "sc", name: "Seychelles" })
Country.find_or_create_by({ code: "sl", name: "Sierra Leone" })
Country.find_or_create_by({ code: "sg", name: "Singapore" })
Country.find_or_create_by({ code: "sx", name: "Sint Maarten (Dutch part)" })
Country.find_or_create_by({ code: "sk", name: "Slovakia" })
Country.find_or_create_by({ code: "si", name: "Slovenia" })
Country.find_or_create_by({ code: "sb", name: "Solomon Islands" })
Country.find_or_create_by({ code: "so", name: "Somalia" })
Country.find_or_create_by({ code: "za", name: "South Africa" })
Country.find_or_create_by({ code: "gs", name: "South Georgia and the South Sandwich Islands" })
Country.find_or_create_by({ code: "ss", name: "South Sudan" })
Country.find_or_create_by({ code: "es", name: "Spain" })
Country.find_or_create_by({ code: "lk", name: "Sri Lanka" })
Country.find_or_create_by({ code: "sd", name: "Sudan" })
Country.find_or_create_by({ code: "sr", name: "Suriname" })
Country.find_or_create_by({ code: "sj", name: "Svalbard and Jan Mayen" })
Country.find_or_create_by({ code: "sz", name: "Swaziland" })
Country.find_or_create_by({ code: "se", name: "Sweden" })
Country.find_or_create_by({ code: "ch", name: "Switzerland" })
Country.find_or_create_by({ code: "sy", name: "Syrian Arab Republic" })
Country.find_or_create_by({ code: "tw", name: "Taiwan, Province of China" })
Country.find_or_create_by({ code: "tj", name: "Tajikistan" })
Country.find_or_create_by({ code: "tz", name: "Tanzania, United Republic of" })
Country.find_or_create_by({ code: "th", name: "Thailand" })
Country.find_or_create_by({ code: "tl", name: "Timor-Leste" })
Country.find_or_create_by({ code: "tg", name: "Togo" })
Country.find_or_create_by({ code: "tk", name: "Tokelau" })
Country.find_or_create_by({ code: "to", name: "Tonga" })
Country.find_or_create_by({ code: "tt", name: "Trinidad and Tobago" })
Country.find_or_create_by({ code: "tn", name: "Tunisia" })
Country.find_or_create_by({ code: "tr", name: "Turkey" })
Country.find_or_create_by({ code: "tm", name: "Turkmenistan" })
Country.find_or_create_by({ code: "tc", name: "Turks and Caicos Islands" })
Country.find_or_create_by({ code: "tv", name: "Tuvalu" })
Country.find_or_create_by({ code: "ug", name: "Uganda" })
Country.find_or_create_by({ code: "ua", name: "Ukraine" })
Country.find_or_create_by({ code: "ae", name: "United Arab Emirates" })
Country.find_or_create_by({ code: "gb", name: "United Kingdom" })
Country.find_or_create_by({ code: "us", name: "United States" })
Country.find_or_create_by({ code: "um", name: "United States Minor Outlying Islands" })
Country.find_or_create_by({ code: "uy", name: "Uruguay" })
Country.find_or_create_by({ code: "uz", name: "Uzbekistan" })
Country.find_or_create_by({ code: "vu", name: "Vanuatu" })
Country.find_or_create_by({ code: "ve", name: "Venezuela, Bolivarian Republic of" })
Country.find_or_create_by({ code: "vn", name: "Viet Nam" })
Country.find_or_create_by({ code: "vg", name: "Virgin Islands, British" })
Country.find_or_create_by({ code: "vi", name: "Virgin Islands, U.S." })
Country.find_or_create_by({ code: "wf", name: "Wallis and Futuna" })
Country.find_or_create_by({ code: "eh", name: "Western Sahara" })
Country.find_or_create_by({ code: "ye", name: "Yemen" })
Country.find_or_create_by({ code: "zm", name: "Zambia" })
Country.find_or_create_by({ code: "zw", name: "Zimbabwe" })

# Non-ISO-3166 countries

Country.find_or_create_by({ code: "scotland", name: "Scotland" })
Country.find_or_create_by({ code: "wales", name: "Wales" })
Country.find_or_create_by({ code: "england", name: "England" })
Country.find_or_create_by({ code: "northern-ireland", name: "Northern Ireland" })
Country.find_or_create_by({ code: "kosovo", name: "Kosovo, Republic of" })
